{{- if .Values.cloudsql.create }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-db-credentials
type: Opaque
data:
  username: {{ .Values.cloudsql.db_credentials.username }}
  password: {{ .Values.cloudsql.db_credentials.password }}
{{- end }}