{{- if .Values.cloudsql.create }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-instance-credentials
type: Opaque
data:
  credentials.json: {{ .Values.cloudsql.instance_credentials.credentialsjson }}
{{- end }}